version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  init-script:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/

volumes:
  mongo_data:
